Employee_list/employee/urls.py
from django.urls import path

from django.conf.urls.static import static
from django.conf import settings
from .views import EmployeeListView, JSONListView, EmployeeDetailView, EmployeeCreateView, EmployeeUpdateView, EmployeeDeleteView, AjaxDetailView

app_name = 'employee'
urlpatterns = [
    path('employee/ajax', AjaxDetailView.as_view(), name='employee_ajax'),
    path('employee/json', JSONListView.as_view(), name='json'),
    path('employee/<int:pk>/delete/', EmployeeDeleteView.as_view(), name='delete_employee'),
    path('employee/<int:pk>/edit/', EmployeeUpdateView.as_view(), name='edit_employee'),
    path('employee/new/', EmployeeCreateView.as_view(), name='new_employee'),
    path('employee/<int:pk>/', EmployeeDetailView.as_view(), name='employee_detail'),
    path('', EmployeeListView.as_view(), name='index'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Employee_list/employee_list/urls.py
from django.contrib import admin
from django.urls import path, include

from employee.router import router

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee.urls')),
    path('api/', include(router.urls)),
]

Employee_list/employee/views.py
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Employee


class EmployeeListView(ListView):
    model = Employee
    template_name = 'index.html'
    paginate_by = 10

    def get_ordering(self):
        sort_employee = self.request.GET.get('employee_sort')
        return sort_employee


class JSONResponseMixin:

    def render_to_json_response(self, context, **response_kwargs):
        return JsonResponse(
            self.get_data(context), safe=False,
            **response_kwargs
        )

    def get_data(self, context):
        context = list(context.values())
        return context


class JSONListView(JSONResponseMixin, EmployeeListView):
    def render_to_response(self, context, **response_kwargs):
        return self.render_to_json_response(context['object_list'])


class AjaxDetailView(TemplateView):
    template_name = 'employee_ajax.html'


class EmployeeDetailView(DetailView):
    model = Employee
    template_name = 'employee_detail.html'


class EmployeeCreateView(CreateView):
    model = Employee
    template_name = 'new_employee.html'
    fields = ['first_name', 'last_name', 'employment_date', 'job_title', 'description', 'photo']
    success_url = reverse_lazy('employee:index')


class EmployeeUpdateView(UpdateView):
    model = Employee
    template_name = 'edit_employee.html'
    fields = ['first_name', 'last_name', 'employment_date', 'job_title', 'description', 'photo']
    success_url = reverse_lazy('employee:index')


class EmployeeDeleteView(DeleteView):
    model = Employee
    template_name = 'delete_employee.html'
    success_url = reverse_lazy('employee:index')

Employee_list/employee/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
    <meta content="ie=edge" http-equiv="X-UA-Compatible">

    <!-- Bootstrap CSS -->
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" rel="stylesheet">

    <!-- Google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400"
          rel="stylesheet">

    <link crossorigin="anonymous" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
          integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" rel="stylesheet">

    <link href="{% static 'employee/style.css' %}" rel="stylesheet">

    <title>{% block title %}{{ title }}{% endblock %} - Employee List</title>
</head>
<body>
<nav class="navbar navbar-expand-md  navbar-dark bg-dark justify-content-center justify-content-md-start mb-0">
    <div class="nav-left">
        <h1><a href="{% url 'employee:index' %}">Employee List</a></h1>
    </div>

    <div class="nav-right">
        <h2><a href="{% url 'employee:new_employee' %}">New Employee</a></h2>
    </div>
</nav>
{% block content %}

{% endblock content %}
<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
{% block script %}
{% endblock %}
</body>
</html>

Employee_list/employee/templates/delete_employee.html
{% extends 'base.html' %}


  {% block content %}
      <div>
          <h1>Delete Student</h1>
          <form action="" method="post">
              {% csrf_token %}
              <p>Are you sure you want to delete "{{ employee.first_name }}"</p>
              <input type="submit" value="Confirm">
          </form>
      </div>
  {% endblock content %}

Employee_list/employee/templates/edit_employee.html
{%  extends 'base.html' %}

{% block content %}
<div>
    <h1>Edit Student</h1>
    <form action="" method="post" enctype="multipart/form-data">
        <fieldset>
            <legend>Edit Employee Details:</legend>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update">
        </fieldset>
    </form>
</div>
{% endblock content %}

Employee_list/employee/templates/employee_ajax.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid mt-3">
    <table id="ajax_employee_table">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Surname</th>
            <th>Job Title</th>
            <th>Date Started</th>
            <th>Description</th>
            <th>Photo</th>
        </tr>
    </table>
</div>
{% endblock %}
{% block script %}
<script>
$.ajax({
               url: 'http://127.0.0.1:8000/employee/json',
               type: 'GET',
               processData: true,
               dataType: 'json',
               success: function(data) {
                 var employee_data = '';
                 $.each(data, function(key, value){
                    employee_data +='<tr>';
                    employee_data += '<td>' + value.id + '</td>';
                    employee_data += '<td>' + value.first_name + '</td>';
                    employee_data += '<td>' + value.last_name + '</td>';
                    employee_data += '<td>' + value.job_title + '</td>';
                    employee_data += '<td>' + value.employment_date + '</td>';
                    employee_data += '<td>' + value.description + '</td>';
                    employee_data += '<td>' + value.photo + '</td>';
                    employee_data += '</tr>';
                 });
                 $('#ajax_employee_table').append(employee_data);
                 }
});


</script>
{% endblock %}

Employee_list/employee/templates/employee_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid d-flex justify-content-center mt-1">
    <div class="media">
        {% if employee.photo %}
        <img alt="" src="{{ employee.photo.url }}"/>
        {% else %}
            <img src="{% static 'employee/images/default.png' %}" alt="" />
        {% endif %}
        <div class="media-body pl-2">
            <p>Name: {{ employee.first_name }}</p>
            <p>Surname: {{ employee.last_name }}</p>
            <p>Date Started: {{ employee.employment_date }}</p>
            <p>Description: {{ employee.description }}</p>
            <p><a href="{% url 'employee:edit_employee' employee.pk %}">Edit Employee</a></p>
            <p><a href="{% url 'employee:delete_employee' employee.pk %}">Delete Employee</a></p>
        </div>
    </div>
</div>
{% endblock %}

Employee_list/employee/templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="container-fluid mt-0 index-image">
    <table>
        <thead>
        <tr>
            <th><a href="{% url 'employee:index' %}?employee_sort=first_name">Name</a></th>
            <th><a href="{% url 'employee:index' %}?employee_sort=last_name">Surname</a></th>
            <th><a href="{% url 'employee:index' %}?employee_sort=job_title">Job title</a></th>
            <th><a href="{% url 'employee:index' %}?employee_sort=employment_date">Date started</a></th>
            <th>Edit/Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for employee in object_list %}
        <tr>
            <td><a href="{% url 'employee:employee_detail' employee.pk %}">{{ employee.first_name }}</a></td>
            <td>{{ employee.last_name }}</td>
            <td>{{ employee.job_title }}</td>
            <td>{{ employee.employment_date }}</td>
            <td><a href="{% url 'employee:edit_employee' employee.pk %}"><i class="fas fa-user-edit edit_employee"></i></a>
                <a href="{% url 'employee:delete_employee' employee.pk %}"><i
                        class="fas fa-user-times delete_employee pl-1"></i></a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if is_paginated %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
        {% else %}
        <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
        {% else %}
        <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
    </ul>
    {% endif %}
</div>
{% endblock %}

Employee_list/employee/templates/new_employee.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid form-group">
    <form action="" method="Post" enctype="multipart/form-data">
        <fieldset>
            <legend>New Employee Details:</legend>
        {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" value="Create"/>
        </fieldset>
    </form>
</div>
{% endblock content%}